# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2019.1.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2019.1.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matteo/CLionProjects/Project_Alpha

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matteo/CLionProjects/Project_Alpha/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2019.1.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2019.1.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matteo/CLionProjects/Project_Alpha/cmake-build-debug/CMakeFiles /home/matteo/CLionProjects/Project_Alpha/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matteo/CLionProjects/Project_Alpha/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project_Alpha_ROOT

# Build rule for target.
Project_Alpha_ROOT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project_Alpha_ROOT
.PHONY : Project_Alpha_ROOT

# fast build rule for target.
Project_Alpha_ROOT/fast:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/build
.PHONY : Project_Alpha_ROOT/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

Archer.o: Archer.cpp.o

.PHONY : Archer.o

# target to build an object file
Archer.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Archer.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Archer.cpp.o
.PHONY : Archer.cpp.o

Archer.i: Archer.cpp.i

.PHONY : Archer.i

# target to preprocess a source file
Archer.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Archer.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Archer.cpp.i
.PHONY : Archer.cpp.i

Archer.s: Archer.cpp.s

.PHONY : Archer.s

# target to generate assembly for a file
Archer.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Archer.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Archer.cpp.s
.PHONY : Archer.cpp.s

Boss.o: Boss.cpp.o

.PHONY : Boss.o

# target to build an object file
Boss.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Boss.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Boss.cpp.o
.PHONY : Boss.cpp.o

Boss.i: Boss.cpp.i

.PHONY : Boss.i

# target to preprocess a source file
Boss.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Boss.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Boss.cpp.i
.PHONY : Boss.cpp.i

Boss.s: Boss.cpp.s

.PHONY : Boss.s

# target to generate assembly for a file
Boss.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Boss.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Boss.cpp.s
.PHONY : Boss.cpp.s

Chest.o: Chest.cpp.o

.PHONY : Chest.o

# target to build an object file
Chest.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Chest.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Chest.cpp.o
.PHONY : Chest.cpp.o

Chest.i: Chest.cpp.i

.PHONY : Chest.i

# target to preprocess a source file
Chest.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Chest.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Chest.cpp.i
.PHONY : Chest.cpp.i

Chest.s: Chest.cpp.s

.PHONY : Chest.s

# target to generate assembly for a file
Chest.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Chest.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Chest.cpp.s
.PHONY : Chest.cpp.s

Enemy.o: Enemy.cpp.o

.PHONY : Enemy.o

# target to build an object file
Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Enemy.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Enemy.cpp.o
.PHONY : Enemy.cpp.o

Enemy.i: Enemy.cpp.i

.PHONY : Enemy.i

# target to preprocess a source file
Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Enemy.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Enemy.cpp.i
.PHONY : Enemy.cpp.i

Enemy.s: Enemy.cpp.s

.PHONY : Enemy.s

# target to generate assembly for a file
Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Enemy.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Enemy.cpp.s
.PHONY : Enemy.cpp.s

GameCharacter.o: GameCharacter.cpp.o

.PHONY : GameCharacter.o

# target to build an object file
GameCharacter.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/GameCharacter.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/GameCharacter.cpp.o
.PHONY : GameCharacter.cpp.o

GameCharacter.i: GameCharacter.cpp.i

.PHONY : GameCharacter.i

# target to preprocess a source file
GameCharacter.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/GameCharacter.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/GameCharacter.cpp.i
.PHONY : GameCharacter.cpp.i

GameCharacter.s: GameCharacter.cpp.s

.PHONY : GameCharacter.s

# target to generate assembly for a file
GameCharacter.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/GameCharacter.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/GameCharacter.cpp.s
.PHONY : GameCharacter.cpp.s

Hero.o: Hero.cpp.o

.PHONY : Hero.o

# target to build an object file
Hero.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Hero.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Hero.cpp.o
.PHONY : Hero.cpp.o

Hero.i: Hero.cpp.i

.PHONY : Hero.i

# target to preprocess a source file
Hero.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Hero.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Hero.cpp.i
.PHONY : Hero.cpp.i

Hero.s: Hero.cpp.s

.PHONY : Hero.s

# target to generate assembly for a file
Hero.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Hero.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Hero.cpp.s
.PHONY : Hero.cpp.s

Item.o: Item.cpp.o

.PHONY : Item.o

# target to build an object file
Item.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Item.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Item.cpp.o
.PHONY : Item.cpp.o

Item.i: Item.cpp.i

.PHONY : Item.i

# target to preprocess a source file
Item.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Item.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Item.cpp.i
.PHONY : Item.cpp.i

Item.s: Item.cpp.s

.PHONY : Item.s

# target to generate assembly for a file
Item.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Item.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Item.cpp.s
.PHONY : Item.cpp.s

Knight.o: Knight.cpp.o

.PHONY : Knight.o

# target to build an object file
Knight.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Knight.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Knight.cpp.o
.PHONY : Knight.cpp.o

Knight.i: Knight.cpp.i

.PHONY : Knight.i

# target to preprocess a source file
Knight.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Knight.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Knight.cpp.i
.PHONY : Knight.cpp.i

Knight.s: Knight.cpp.s

.PHONY : Knight.s

# target to generate assembly for a file
Knight.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Knight.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Knight.cpp.s
.PHONY : Knight.cpp.s

Mage.o: Mage.cpp.o

.PHONY : Mage.o

# target to build an object file
Mage.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Mage.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Mage.cpp.o
.PHONY : Mage.cpp.o

Mage.i: Mage.cpp.i

.PHONY : Mage.i

# target to preprocess a source file
Mage.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Mage.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Mage.cpp.i
.PHONY : Mage.cpp.i

Mage.s: Mage.cpp.s

.PHONY : Mage.s

# target to generate assembly for a file
Mage.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Mage.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Mage.cpp.s
.PHONY : Mage.cpp.s

Map.o: Map.cpp.o

.PHONY : Map.o

# target to build an object file
Map.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Map.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Map.cpp.o
.PHONY : Map.cpp.o

Map.i: Map.cpp.i

.PHONY : Map.i

# target to preprocess a source file
Map.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Map.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Map.cpp.i
.PHONY : Map.cpp.i

Map.s: Map.cpp.s

.PHONY : Map.s

# target to generate assembly for a file
Map.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Map.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Map.cpp.s
.PHONY : Map.cpp.s

Tile.o: Tile.cpp.o

.PHONY : Tile.o

# target to build an object file
Tile.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Tile.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Tile.cpp.o
.PHONY : Tile.cpp.o

Tile.i: Tile.cpp.i

.PHONY : Tile.i

# target to preprocess a source file
Tile.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Tile.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Tile.cpp.i
.PHONY : Tile.cpp.i

Tile.s: Tile.cpp.s

.PHONY : Tile.s

# target to generate assembly for a file
Tile.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Tile.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Tile.cpp.s
.PHONY : Tile.cpp.s

Weapon.o: Weapon.cpp.o

.PHONY : Weapon.o

# target to build an object file
Weapon.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Weapon.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Weapon.cpp.o
.PHONY : Weapon.cpp.o

Weapon.i: Weapon.cpp.i

.PHONY : Weapon.i

# target to preprocess a source file
Weapon.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Weapon.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Weapon.cpp.i
.PHONY : Weapon.cpp.i

Weapon.s: Weapon.cpp.s

.PHONY : Weapon.s

# target to generate assembly for a file
Weapon.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/Weapon.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Weapon.cpp.s
.PHONY : Weapon.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Project_Alpha_ROOT.dir/build.make CMakeFiles/Project_Alpha_ROOT.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... Project_Alpha_ROOT"
	@echo "... rebuild_cache"
	@echo "... core"
	@echo "... Archer.o"
	@echo "... Archer.i"
	@echo "... Archer.s"
	@echo "... Boss.o"
	@echo "... Boss.i"
	@echo "... Boss.s"
	@echo "... Chest.o"
	@echo "... Chest.i"
	@echo "... Chest.s"
	@echo "... Enemy.o"
	@echo "... Enemy.i"
	@echo "... Enemy.s"
	@echo "... GameCharacter.o"
	@echo "... GameCharacter.i"
	@echo "... GameCharacter.s"
	@echo "... Hero.o"
	@echo "... Hero.i"
	@echo "... Hero.s"
	@echo "... Item.o"
	@echo "... Item.i"
	@echo "... Item.s"
	@echo "... Knight.o"
	@echo "... Knight.i"
	@echo "... Knight.s"
	@echo "... Mage.o"
	@echo "... Mage.i"
	@echo "... Mage.s"
	@echo "... Map.o"
	@echo "... Map.i"
	@echo "... Map.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... Weapon.o"
	@echo "... Weapon.i"
	@echo "... Weapon.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

